### ISSUE TITLE
Fedora 36 build error: field `sources` has incomplete type `std::array<GDALRasterBand*, 12>`

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteosatlib#31] opened 2022-06-07 07:20 UTC
Full log: https://simc.arpae.it/moncic-ci/meteosatlib/202206061253/master/fedora36/build.log

Relevant bit:
```
make[2]: Entering directory '/root/rpmbuild/BUILD/meteosatlib/gdal'
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H    -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Wall -Wextra -Wno-unused-parameter -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c -o msatgdalplugin.lo msatgdalplugin.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wall -Wextra -Wno-unused-parameter -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c msatgdalplugin.cpp  -fPIC -DPIC -o .libs/msatgdalplugin.o
make[2]: Leaving directory '/root/rpmbuild/BUILD/meteosatlib/gdal'
In file included from msatgdalplugin.cpp:27:
reflectance/reflectance.h:26:37: error: field 'sources' has incomplete type 'std::array<GDALRasterBand*, 12>'
```

**Comment by spanezz** [comment] 2022-06-15 10:53
Closing as duplicate of #29

**Closed by spanezz** 2022-06-15 10:53 UTC
Labels: bug
